version: '3.8'

services:

  postgres-user:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres_user
    restart: always
    environment:
      POSTGRES_USER: user_service
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres-portfolio:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres_portfolio
    restart: always
    environment:
      POSTGRES_USER: asset_user
      POSTGRES_DB: asset_tracker
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ../asset-tracker-api-user-service
    container_name: user_service
    restart: always
    depends_on:
      - postgres-user
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_service

  portfolio-service:
    build: ../asset-tracker-api-portfolio-service
    container_name: portfolio_service
    restart: always
    depends_on:
      - postgres-portfolio
      - market-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-portfolio:5432/asset_tracker
      SPRING_DATASOURCE_USERNAME: asset_user
      MARKET_SERVICE_URL: http://market-service:8080

  market-service:
    build: ../asset-tracker-api-market-service
    container_name: market_service
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - .env

volumes:
  postgres_user_data:
  postgres_data: